image_root: '/mnt/localdata/karoui/datasets/marvl/marvl-images/' 
#ann_root: '/mnt/localdata/karoui/datasets/marvl/marvl-annotations/machine_translations/' #english translations
ann_root: '/mnt/localdata/karoui/datasets/marvl/marvl-annotations/' #original translations
eng: False


# set pretrained as a file path or an url
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_nlvr.pth'

ml_model_path_tr_cls: "/mnt/localdata/karoui/code/Multilingual-CLIP/src/TeacherLearning/experiments/nlvr2/tr_cls2022-04-26_19-03-07/weights"
ml_model_path_tr_avg: "/mnt/localdata/karoui/code/Multilingual-CLIP/src/TeacherLearning/experiments/nlvr2/tr_avg2022-04-27_11-37-29/weights"


# set tokenizer 
tokenizer_de : "dbmdz/bert-base-german-cased" #german
tokenizer_en: 'bert-base-uncased' # english
tokenizer_tr: "dbmdz/bert-base-turkish-cased" #turkish

#size of vit model; base or large
vit: 'base'
batch_size_train: 16 
batch_size_test: 64 
vit_grad_ckpt: False
vit_ckpt_layer: 0
max_epoch: 15

image_size: 384

# optimizer
weight_decay: 0.05
init_lr: 3e-5
min_lr: 0


